## NUMPY

In [1]:
import numpy as np

In [2]:
np.version

<module 'numpy.version' from '/home/xs295-ashson/miniconda3/envs/av/lib/python3.9/site-packages/numpy/version.py'>

In [3]:
#creating a numpy array

np.array([1,4,2,7,3])

array([1, 4, 2, 7, 3])

In [7]:
#Difference Between List and Numpy array

a=[1,2,3,4,5]
print(a*2)

b=np.array([1,2,3,4,5])
b*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


array([ 2,  4,  6,  8, 10])

In [8]:
#Create a matrix using NumPy

a=[[1,2,3],
 [3,2,1],
 [5,6,7]]

In [10]:
a

[[1, 2, 3], [3, 2, 1], [5, 6, 7]]

In [11]:
a=np.array(a)

In [12]:
a

array([[1, 2, 3],
       [3, 2, 1],
       [5, 6, 7]])

In [13]:
a[0][2]

3

In [14]:
# Creating a 3x3 array using random function

np.random.randint(0,10,(3,3))

array([[5, 7, 2],
       [3, 4, 0],
       [8, 3, 4]])

In [15]:
np.random.randint(0,10,(3,3))

array([[8, 9, 9],
       [5, 2, 0],
       [7, 0, 6]])

In [16]:
#fixing the random seed

np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [17]:

np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [18]:
# Create a 3x4 integer array filled with zeroes

np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
# Create a 3x4 integer array filled with ones

np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
# Create a 4x4 identity matrix

np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [22]:
# create a matrix filled with specific number

np.full((2,6),7)

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

#### Concatenation

In [23]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(0,10,(3,3))

print(a)
b

[[4 7 6]
 [8 8 1]
 [6 7 7]]


array([[8, 1, 5],
       [9, 8, 9],
       [4, 3, 0]])

In [25]:
#ROW WISE

np.concatenate([a,b],axis=0)

array([[4, 7, 6],
       [8, 8, 1],
       [6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0]])

In [26]:
#COLUMN WISE

np.concatenate([a,b],axis=1)

array([[4, 7, 6, 8, 1, 5],
       [8, 8, 1, 9, 8, 9],
       [6, 7, 7, 4, 3, 0]])

##  SciPy

In [27]:
import scipy

In [28]:
scipy.__version__

'1.6.2'

In [30]:
#Compute the nth derivative of a function
from scipy.misc import derivative

In [31]:
def func(x):
    return x**2+x+1

In [32]:
func(4)

21

In [33]:
derivative(func=func,x0=4)

9.0

In [34]:
#2nd derivative

derivative(func=func,x0=4,n=2)

2.0

#### Permutation and Combination

In [36]:
# Combinations

from scipy.special import comb
#total num. of combinations from 4 different values taken 2 at a time
#  4C2
com=comb(4,2)
com

6.0

In [37]:
# Permutation

from scipy.special import perm
#total num. of combinations from 4 different values taken 2 at a time
#  4P2
per=perm(4,2)
per

12.0

In [38]:
from scipy import constants

print(constants.pi)

3.141592653589793


In [39]:
dir(constants)

['Avogadro',
 'Boltzmann',
 'Btu',
 'Btu_IT',
 'Btu_th',
 'ConstantWarning',
 'G',
 'Julian_year',
 'N_A',
 'Planck',
 'R',
 'Rydberg',
 'Stefan_Boltzmann',
 'Wien',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_obsolete_constants',
 'acre',
 'alpha',
 'angstrom',
 'arcmin',
 'arcminute',
 'arcsec',
 'arcsecond',
 'astronomical_unit',
 'atm',
 'atmosphere',
 'atomic_mass',
 'atto',
 'au',
 'bar',
 'barrel',
 'bbl',
 'blob',
 'c',
 'calorie',
 'calorie_IT',
 'calorie_th',
 'carat',
 'centi',
 'codata',
 'constants',
 'convert_temperature',
 'day',
 'deci',
 'degree',
 'degree_Fahrenheit',
 'deka',
 'dyn',
 'dyne',
 'e',
 'eV',
 'electron_mass',
 'electron_volt',
 'elementary_charge',
 'epsilon_0',
 'erg',
 'exa',
 'exbi',
 'femto',
 'fermi',
 'find',
 'fine_structure',
 'fluid_ounce',
 'fluid_ounce_US',
 'fluid_ounce_imp',
 'foot',
 'g',
 'gallon',
 'gallon_US',
 'gallon_imp',
 'gas_constant'

In [42]:
constants.week


604800.0

In [43]:
constants.Planck

6.62607015e-34

In [44]:
constants.Avogadro

6.02214076e+23

In [47]:
pip install opencv

ERROR: Could not find a version that satisfies the requirement opencv
ERROR: No matching distribution found for opencv
Note: you may need to restart the kernel to use updated packages.
